// Oefeningenbibliotheek, gebaseerd op de apparatuur in Sportcentrum Hierden.
// Foto's staan in /public/equipment.

export type Muscle =
  | "borst"
  | "schouders"
  | "rug"
  | "biceps"
  | "triceps"
  | "quads"
  | "hamstrings"
  | "billen"
  | "kuiten"
  | "adductoren"
  | "buik"
  | "onderrug";

export type LoadType = "machine" | "kabel" | "dumbbell" | "stang" | "smith" | "lichaamsgewicht";

export interface Exercise {
  id: string;
  name: string;
  muscle: Muscle; // primaire spiergroep, telt voor progressie per spiergroep
  secondary?: Muscle[];
  equipment: string; // welk apparaat in jullie gym
  photo: string;
  setup: string; // hoe je het apparaat instelt
  tips: string[];
  load: LoadType;
  increment: number; // kg per stap omhoog
  isolation: boolean; // isolatie-oefening: dropset toegestaan
  exclBar?: boolean; // gewicht loggen zonder stang
  plates?: boolean; // gewicht loggen als plaatnummer (machines zonder kg op het blok)
  alternatives: string[]; // als het apparaat bezet is
}

const yt = (q: string) => `https://www.youtube.com/results?search_query=${encodeURIComponent(q + " uitvoering")}`;
export const videoUrl = (e: Exercise) => yt(e.name);

export const EXERCISES: Exercise[] = [
  // ---------- BORST ----------
  {
    id: "incline-smith",
    name: "Incline bench press (Smith)",
    muscle: "borst",
    secondary: ["schouders", "triceps"],
    equipment: "Witte Smith machine",
    photo: "/equipment/smith-machine.webp",
    setup: "Bankje in het rek op de 2e of 3e stand schuin (±30°). Stang zakt net boven je bovenste borst.",
    tips: [
      "Schouderbladen naar achter en omlaag, borst omhoog.",
      "Ellebogen iets naar binnen (±45°), niet wijd uit.",
      "Rustig zakken tot je borst, krachtig omhoog.",
    ],
    load: "smith",
    increment: 2.5,
    isolation: false,
    exclBar: true,
    alternatives: ["incline-db-press", "chest-press"],
  },
  {
    id: "chest-press",
    name: "Chest press machine",
    muscle: "borst",
    secondary: ["schouders", "triceps"],
    equipment: "Impulse Chest Press",
    photo: "/equipment/chest-press.webp",
    setup: "Stoel zo hoog dat de handvatten op borsthoogte zitten (tepellijn).",
    tips: ["Rug tegen het kussen houden.", "Niet je ellebogen helemaal op slot drukken.", "Langzaam terug, 2 tellen."],
    load: "machine",
    increment: 5,
    isolation: false,
    alternatives: ["db-flat-press", "incline-db-press"],
  },
  {
    id: "pec-deck",
    name: "Pec deck",
    muscle: "borst",
    equipment: "Impulse Pectoral (butterfly)",
    photo: "/equipment/pec-deck.webp",
    setup: "Stoel zo dat je ellebogen net onder schouderhoogte tegen de kussens zitten.",
    tips: ["Knijp je borst samen in het midden, 1 tel vasthouden.", "Niet met je armen trekken, de borst doet het werk."],
    load: "machine",
    increment: 5,
    isolation: true,
    alternatives: ["cable-fly", "pec-fly-machine"],
  },
  {
    id: "pec-fly-machine",
    name: "Pec fly (combi-machine)",
    muscle: "borst",
    equipment: "Impulse Pec Fly / Rear Delt",
    photo: "/equipment/pec-fly-rear-delt.webp",
    setup: "Handvatten naar voren draaien voor de borstvariant, stoel op schouderhoogte.",
    tips: ["Lichte buiging in de ellebogen vasthouden.", "Gecontroleerd terug, niet laten klappen."],
    load: "machine",
    increment: 5,
    isolation: true,
    alternatives: ["pec-deck", "cable-fly"],
  },
  {
    id: "cable-fly",
    name: "Cable fly",
    muscle: "borst",
    equipment: "Evolve-station, twee kolommen tegenover elkaar",
    photo: "/equipment/evolve-cable.webp",
    setup: "Beide katrollen op schouderhoogte, enkele handgrepen. Stap één pas naar voren tussen de kolommen.",
    tips: ["Armen in een grote boog naar voren, alsof je een boom omhelst.", "Handen komen samen voor je borst."],
    load: "kabel",
    increment: 2.5,
    isolation: true,
    alternatives: ["pec-deck", "pec-fly-machine"],
  },
  {
    id: "bench-press",
    name: "Bench press",
    muscle: "borst",
    secondary: ["schouders", "triceps"],
    equipment: "Vlakke bench met halterstang",
    photo: "/equipment/bench-press.webp",
    setup: "Ogen recht onder de stang. Handen iets breder dan schouderbreedte.",
    tips: [
      "Voeten plat op de grond, schouderbladen samen.",
      "Stang zakt naar je onderste borst, ellebogen ±45°.",
      "Zwaar? Vraag iemand om te spotten.",
    ],
    load: "stang",
    increment: 2.5,
    isolation: false,
    alternatives: ["db-flat-press", "chest-press"],
  },
  {
    id: "incline-db-press",
    name: "Incline dumbbell press",
    muscle: "borst",
    secondary: ["schouders", "triceps"],
    equipment: "Verstelbaar bankje + dumbbells",
    photo: "/equipment/dumbbells-bench.webp",
    setup: "Bankje ±30° schuin. Log het gewicht van één dumbbell.",
    tips: ["Dumbbells zakken naast je borst, niet naast je schouders.", "Bovenin niet tegen elkaar tikken."],
    load: "dumbbell",
    increment: 2,
    isolation: false,
    alternatives: ["incline-smith", "chest-press"],
  },
  {
    id: "db-flat-press",
    name: "Dumbbell press (vlak)",
    muscle: "borst",
    secondary: ["schouders", "triceps"],
    equipment: "Verstelbaar bankje + dumbbells",
    photo: "/equipment/dumbbells-bench.webp",
    setup: "Bankje plat. Log het gewicht van één dumbbell.",
    tips: ["Schouderbladen samen, ellebogen ±45°.", "Diep zakken voor een goede stretch."],
    load: "dumbbell",
    increment: 2,
    isolation: false,
    alternatives: ["bench-press", "chest-press"],
  },

  // ---------- SCHOUDERS ----------
  {
    id: "shoulder-press",
    name: "Shoulder press machine",
    muscle: "schouders",
    secondary: ["triceps"],
    equipment: "Impulse Shoulder Press",
    photo: "/equipment/shoulder-press.webp",
    setup: "Stoel zo dat de handvatten net boven je schouders beginnen.",
    tips: ["Rug tegen het kussen, niet hol trekken.", "Omhoog duwen tot net voor slot."],
    load: "machine",
    increment: 5,
    isolation: false,
    alternatives: ["db-shoulder-press"],
  },
  {
    id: "db-shoulder-press",
    name: "Dumbbell shoulder press",
    muscle: "schouders",
    secondary: ["triceps"],
    equipment: "Verstelbaar bankje + dumbbells",
    photo: "/equipment/dumbbells-bench.webp",
    setup: "Bankje bijna rechtop (één stand onder recht). Log één dumbbell.",
    tips: ["Dumbbells zakken tot oorhoogte.", "Core aanspannen, niet achterover leunen."],
    load: "dumbbell",
    increment: 2,
    isolation: false,
    alternatives: ["shoulder-press"],
  },
  {
    id: "cable-lateral",
    name: "Lateral raise (kabel)",
    muscle: "schouders",
    equipment: "Evolve-station, één kolom",
    photo: "/equipment/evolve-cable.webp",
    setup: "Katrol helemaal laag, enkele handgreep. Ga zijwaarts naast de kolom staan en pak de greep met je verste hand.",
    tips: ["Arm zijwaarts omhoog tot schouderhoogte, niet hoger.", "Lichte buiging in je elleboog.", "Niet zwaaien: liever lichter en strak."],
    load: "kabel",
    increment: 2.5,
    isolation: true,
    alternatives: ["db-lateral"],
  },
  {
    id: "db-lateral",
    name: "Lateral raise (dumbbells)",
    muscle: "schouders",
    equipment: "Dumbbells",
    photo: "/equipment/dumbbells-bench.webp",
    setup: "Staand, dumbbells naast je lichaam. Log één dumbbell.",
    tips: ["Leid met je ellebogen, niet met je handen.", "Tot schouderhoogte, rustig zakken."],
    load: "dumbbell",
    increment: 2,
    isolation: true,
    alternatives: ["cable-lateral"],
  },
  {
    id: "rear-delt-fly",
    name: "Rear delt fly",
    muscle: "schouders",
    secondary: ["rug"],
    equipment: "Impulse Pec Fly / Rear Delt",
    photo: "/equipment/pec-fly-rear-delt.webp",
    setup: "Handvatten naar achteren draaien. Zit met je borst tegen het kussen.",
    tips: ["Armen wijd naar achter, schouderbladen niet te veel samenknijpen.", "Licht gewicht, gevoel in de achterkant van je schouder."],
    load: "machine",
    increment: 5,
    isolation: true,
    alternatives: ["cable-rear-delt"],
  },
  {
    id: "cable-rear-delt",
    name: "Rear delt fly (kabel)",
    muscle: "schouders",
    equipment: "Evolve-station, twee kolommen tegenover elkaar",
    photo: "/equipment/evolve-cable.webp",
    setup: "Katrollen op schouderhoogte, geen handgreep: pak de kabel zelf vast, kruislings.",
    tips: ["Armen gestrekt wijd naar achter trekken.", "Licht en gecontroleerd."],
    load: "kabel",
    increment: 2.5,
    isolation: true,
    alternatives: ["rear-delt-fly"],
  },

  // ---------- RUG ----------
  {
    id: "lat-pulldown",
    name: "Lat pulldown",
    muscle: "rug",
    secondary: ["biceps"],
    equipment: "Impulse Lat Pull",
    photo: "/equipment/lat-pulldown.webp",
    setup: "Kniekussens strak op je bovenbenen. Handen iets breder dan schouders.",
    tips: ["Trek de stang naar je bovenste borst, ellebogen naar je zij.", "Borst omhoog, licht achterover.", "Bovenin volledig strekken."],
    load: "machine",
    increment: 5,
    isolation: false,
    alternatives: ["evolve-pulldown", "pull-up"],
  },
  {
    id: "evolve-pulldown",
    name: "Pulldown (Evolve)",
    muscle: "rug",
    secondary: ["biceps"],
    equipment: "Evolve-station, pulldown",
    photo: "/equipment/evolve-pulldown.webp",
    setup: "Kniekussens strak. Kies de brede stang of de V-greep van het rek.",
    tips: ["Ellebogen omlaag naar je heupen trekken.", "Gecontroleerd terug omhoog."],
    load: "kabel",
    increment: 5,
    isolation: false,
    alternatives: ["lat-pulldown", "pull-up"],
  },
  {
    id: "chest-supported-row",
    name: "Chest supported row",
    muscle: "rug",
    secondary: ["biceps", "schouders"],
    equipment: "Impulse Vertical Row",
    photo: "/equipment/vertical-row.webp",
    setup: "Borstkussen zo dat je de handvatten met gestrekte armen net kunt pakken.",
    tips: ["Borst tegen het kussen houden.", "Ellebogen naar achter, schouderbladen samen.", "1 tel vasthouden achterin."],
    load: "machine",
    increment: 5,
    isolation: false,
    alternatives: ["evolve-mid-row", "one-arm-db-row"],
  },
  {
    id: "evolve-mid-row",
    name: "Seated cable row (Evolve)",
    muscle: "rug",
    secondary: ["biceps"],
    equipment: "Evolve-station, mid row",
    photo: "/equipment/evolve-mid-row.webp",
    setup: "Voeten op de voetplaat, V-greep. Zit rechtop.",
    tips: ["Trek naar je navel, ellebogen langs je lichaam.", "Niet met je rug meezwaaien."],
    load: "kabel",
    increment: 5,
    isolation: false,
    alternatives: ["chest-supported-row", "one-arm-db-row"],
  },
  {
    id: "one-arm-db-row",
    name: "One-arm dumbbell row",
    muscle: "rug",
    secondary: ["biceps"],
    equipment: "Bankje + dumbbell",
    photo: "/equipment/dumbbells-bench.webp",
    setup: "Eén knie en hand op het bankje, rug plat.",
    tips: ["Trek de dumbbell naar je heup, niet naar je schouder.", "Onderin goed laten hangen voor de stretch."],
    load: "dumbbell",
    increment: 2,
    isolation: false,
    alternatives: ["chest-supported-row", "evolve-mid-row"],
  },
  {
    id: "pull-up",
    name: "Pull-ups",
    muscle: "rug",
    secondary: ["biceps"],
    equipment: "Pull-up bar (Evolve of wandrek)",
    photo: "/equipment/pullup-bar.webp",
    setup: "Lukt het nog niet? Kies de Evolve pulldown. Extra gewicht = gewicht dat je toevoegt (anders 0).",
    tips: ["Volledig hangen onderin.", "Borst naar de stang, niet alleen je kin.", "Niet zwaaien."],
    load: "lichaamsgewicht",
    increment: 2.5,
    isolation: false,
    alternatives: ["evolve-pulldown", "lat-pulldown"],
  },
  {
    id: "straight-arm-pulldown",
    name: "Straight arm pulldown",
    muscle: "rug",
    equipment: "Evolve-station, één kolom",
    photo: "/equipment/evolve-cable.webp",
    setup: "Katrol hoog, rechte stang of touw. Iets voorover leunen.",
    tips: ["Armen gestrekt naar je bovenbenen trekken.", "Voel je lats, niet je triceps."],
    load: "kabel",
    increment: 2.5,
    isolation: true,
    alternatives: ["lat-pulldown"],
  },
  {
    id: "back-extension",
    name: "Back extension",
    muscle: "onderrug",
    secondary: ["billen"],
    equipment: "Impulse Back Extension",
    photo: "/equipment/back-extension.webp",
    setup: "Voeten onder de rollen, rugkussen hoog op je rug.",
    tips: ["Rustig naar achter tot rechtop, niet doorbuigen.", "Gecontroleerd terug."],
    load: "machine",
    increment: 5,
    isolation: true,
    alternatives: [],
  },

  // ---------- BICEPS ----------
  {
    id: "bayesian-curl",
    name: "Bayesian curl",
    muscle: "biceps",
    equipment: "Witte Life Fitness, twee kolommen naast elkaar",
    photo: "/equipment/dual-cable-white.webp",
    setup: "Katrol laag, enkele handgreep. Ga met je rug naar de kolom staan en stap één pas naar voren: je arm begint achter je lichaam. Log het plaatnummer van de pin (1-16).",
    tips: ["Elleboog blijft achter je lichaam, beweegt niet naar voren.", "Volledige stretch onderin.", "Per arm loggen."],
    load: "kabel",
    increment: 1,
    plates: true,
    isolation: true,
    alternatives: ["machine-arm-curl", "hammer-curl"],
  },
  {
    id: "machine-arm-curl",
    name: "Arm curl machine",
    muscle: "biceps",
    equipment: "Impulse Arm Curl",
    photo: "/equipment/arm-curl.webp",
    setup: "Stoel zo dat je oksels op de bovenkant van het kussen rusten.",
    tips: ["Volledig strekken onderin.", "Bovenin 1 tel knijpen."],
    load: "machine",
    increment: 5,
    isolation: true,
    alternatives: ["bayesian-curl", "hammer-curl"],
  },
  {
    id: "hammer-curl",
    name: "Hammer curl",
    muscle: "biceps",
    equipment: "Dumbbells",
    photo: "/equipment/dumbbells-bench.webp",
    setup: "Staand, duimen naar boven. Log één dumbbell.",
    tips: ["Ellebogen tegen je zij.", "Niet zwaaien met je rug."],
    load: "dumbbell",
    increment: 2,
    isolation: true,
    alternatives: ["machine-arm-curl"],
  },

  // ---------- TRICEPS ----------
  {
    id: "rope-pushdown",
    name: "Triceps pushdown (touw)",
    muscle: "triceps",
    equipment: "Evolve-station, één kolom",
    photo: "/equipment/evolve-cable.webp",
    setup: "Katrol helemaal hoog, touw van het rek.",
    tips: ["Ellebogen vast tegen je zij.", "Onderin het touw uit elkaar trekken."],
    load: "kabel",
    increment: 2.5,
    isolation: true,
    alternatives: ["seated-dip-machine"],
  },
  {
    id: "cable-overhead-ext",
    name: "Overhead triceps extension (kabel)",
    muscle: "triceps",
    equipment: "Evolve-station, één kolom",
    photo: "/equipment/evolve-cable.webp",
    setup: "Katrol laag of halverwege, touw. Ga met je rug naar de kolom staan, touw achter je hoofd.",
    tips: ["Ellebogen naast je hoofd, wijzen naar voren.", "Volledige stretch achter je hoofd."],
    load: "kabel",
    increment: 2.5,
    isolation: true,
    alternatives: ["rope-pushdown"],
  },
  {
    id: "seated-dip-machine",
    name: "Seated dip machine",
    muscle: "triceps",
    secondary: ["borst"],
    equipment: "Impulse Seated Dip",
    photo: "/equipment/seated-dip.webp",
    setup: "Stoel zo dat de handvatten naast je heupen eindigen.",
    tips: ["Rechtop blijven zitten.", "Duw door tot bijna gestrekt."],
    load: "machine",
    increment: 5,
    isolation: false,
    alternatives: ["dips", "rope-pushdown"],
  },
  {
    id: "dips",
    name: "Dips",
    muscle: "triceps",
    secondary: ["borst"],
    equipment: "Dipstation aan het wandrek of captain's chair",
    photo: "/equipment/dip-station.webp",
    setup: "Lukt het nog niet? Kies de seated dip machine. Extra gewicht = wat je toevoegt (anders 0).",
    tips: ["Zak tot je bovenarmen ongeveer horizontaal zijn.", "Rechtop = meer triceps, voorover = meer borst."],
    load: "lichaamsgewicht",
    increment: 2.5,
    isolation: false,
    alternatives: ["seated-dip-machine"],
  },

  // ---------- BENEN ----------
  {
    id: "leg-press",
    name: "Leg press",
    muscle: "quads",
    secondary: ["billen", "hamstrings"],
    equipment: "Impulse Leg Press / Calf Raise",
    photo: "/equipment/leg-press-calf.webp",
    setup: "Stoel zo dat je knieën onderin ±90° buigen. Voeten op heupbreedte, midden op de plaat.",
    tips: ["Onderrug blijft tegen het kussen.", "Knieën niet op slot bovenin.", "Knieën in lijn met je tenen."],
    load: "machine",
    increment: 5,
    isolation: false,
    alternatives: ["leg-press-horizontal"],
  },
  {
    id: "leg-press-horizontal",
    name: "Leg press (horizontaal)",
    muscle: "quads",
    secondary: ["billen", "hamstrings"],
    equipment: "Horizontale leg press",
    photo: "/equipment/leg-press-horizontal.webp",
    setup: "Stoel zo dat je knieën onderin ±90° buigen.",
    tips: ["Onderrug tegen het kussen.", "Knieën niet op slot."],
    load: "machine",
    increment: 5,
    isolation: false,
    alternatives: ["leg-press"],
  },
  {
    id: "seated-leg-curl",
    name: "Seated leg curl",
    muscle: "hamstrings",
    equipment: "Impulse Seated Leg Curl",
    photo: "/equipment/seated-leg-curl.webp",
    setup: "Knie op één lijn met het draaipunt. Bovenste kussen strak op je bovenbenen.",
    tips: ["Volledig buigen, 1 tel vasthouden.", "Langzaam terug."],
    load: "machine",
    increment: 5,
    isolation: true,
    alternatives: [],
  },
  {
    id: "leg-extension",
    name: "Leg extension",
    muscle: "quads",
    equipment: "Impulse Leg Extension",
    photo: "/equipment/leg-extension.webp",
    setup: "Knie op één lijn met het draaipunt, rol net boven je enkels.",
    tips: ["Bovenin 1 tel knijpen.", "Langzaam zakken, niet laten vallen."],
    load: "machine",
    increment: 5,
    isolation: true,
    alternatives: [],
  },
  {
    id: "standing-glute",
    name: "Standing glute kickback",
    muscle: "billen",
    equipment: "Technogym Standing Gluteus",
    photo: "/equipment/standing-gluteus.webp",
    setup: "Borst tegen het kussen, één voet op de plaat, het andere been achter de rol.",
    tips: ["Duw je been naar achter vanuit je bil, niet vanuit je onderrug.", "Per been loggen."],
    load: "machine",
    increment: 5,
    isolation: true,
    alternatives: ["back-extension"],
  },
  {
    id: "calf-raise",
    name: "Calf raise (leg press)",
    muscle: "kuiten",
    equipment: "Impulse Leg Press / Calf Raise",
    photo: "/equipment/leg-press-calf.webp",
    setup: "Op de leg press: alleen je voorvoeten onderaan de plaat.",
    tips: ["Volledige stretch onderin, 1 tel pauze.", "Helemaal op je tenen bovenin."],
    load: "machine",
    increment: 5,
    isolation: true,
    alternatives: [],
  },
  {
    id: "adductor",
    name: "Adductor",
    muscle: "adductoren",
    equipment: "Impulse Abductor & Adductor",
    photo: "/equipment/abductor-adductor.webp",
    setup: "Kussens aan de binnenkant van je knieën, begin met een comfortabele spreiding.",
    tips: ["Benen samen knijpen, rustig terug."],
    load: "machine",
    increment: 5,
    isolation: true,
    alternatives: [],
  },

  // ---------- BUIK ----------
  {
    id: "captains-leg-raise",
    name: "Leg raises (captain's chair)",
    muscle: "buik",
    equipment: "Captain's chair",
    photo: "/equipment/captains-chair.webp",
    setup: "Onderarmen op de kussens, rug tegen de rugleuning.",
    tips: ["Knieën naar je borst, bekken iets kantelen.", "Niet zwaaien. Te makkelijk? Benen gestrekt."],
    load: "lichaamsgewicht",
    increment: 2.5,
    isolation: true,
    alternatives: ["ab-crunch-machine"],
  },
  {
    id: "ab-crunch-machine",
    name: "Abdominal crunch machine",
    muscle: "buik",
    equipment: "Impulse Abdominal",
    photo: "/equipment/abdominal.webp",
    setup: "Stoel zo dat de handvatten bij je schouders zitten.",
    tips: ["Rol je ruggengraat op, trek niet met je armen.", "Uitademen als je naar voren gaat."],
    load: "machine",
    increment: 5,
    isolation: true,
    alternatives: ["rope-crunch"],
  },
  {
    id: "rope-crunch",
    name: "Rope crunch (kabel)",
    muscle: "buik",
    equipment: "Evolve-station, één kolom",
    photo: "/equipment/evolve-cable.webp",
    setup: "Katrol hoog, touw. Kniel voor de kolom, touw naast je hoofd.",
    tips: ["Rol naar beneden met je buik, heupen blijven stil.", "Ellebogen richting je knieën."],
    load: "kabel",
    increment: 2.5,
    isolation: true,
    alternatives: ["ab-crunch-machine"],
  },
  {
    id: "torso-rotation",
    name: "Torso rotation",
    muscle: "buik",
    equipment: "Impulse Torso Rotation",
    photo: "/equipment/torso-rotation.webp",
    setup: "Knieën tussen de kussens, kies de beginhoek met de pin onderin.",
    tips: ["Draai vanuit je romp, rustig tempo.", "Beide kanten loggen als aparte set."],
    load: "machine",
    increment: 5,
    isolation: true,
    alternatives: ["rope-crunch"],
  },
];

const num = (n: number) => String(Math.round(n * 100) / 100).replace(".", ",");

/** "50 kg" of "plaat 5", afhankelijk van hoe de oefening gelogd wordt. */
export function formatLoad(exerciseId: string, weight: number): string {
  return EXERCISE_MAP[exerciseId]?.plates ? `plaat ${num(weight)}` : `${num(weight)} kg`;
}

export const EXERCISE_MAP: Record<string, Exercise> = Object.fromEntries(EXERCISES.map((e) => [e.id, e]));

export function getExercise(id: string): Exercise {
  const e = EXERCISE_MAP[id];
  if (!e) throw new Error(`Onbekende oefening: ${id}`);
  return e;
}

export const MUSCLE_LABEL: Record<Muscle, string> = {
  borst: "Borst",
  schouders: "Schouders",
  rug: "Rug",
  biceps: "Biceps",
  triceps: "Triceps",
  quads: "Quads",
  hamstrings: "Hamstrings",
  billen: "Billen",
  kuiten: "Kuiten",
  adductoren: "Adductoren",
  buik: "Buik",
  onderrug: "Onderrug",
};
